# Generated by Django 5.1.1 on 2024-09-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_servicios',
            name='fechaFinalizado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
